name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: linux-runner
jobs:
  example-job:
    name: Save output
    steps:
      - run: echo "Hello world"
